### ISSUE TITLE
Avoid duplicate underscore in generate classname

### ISSUE THREAD

**Issue by skogsbaer** [factisresearch/sum_data_types#6]
If the mixin for a DataClass is private, the resulting types have a double underscore in their names. Example:

    mixin _LoginData on __LoginDataBase {
    }

We could change the name generation schema so that we generate `_LoginDataFactory`, `_LoginDataBase` and `_LoginDataImpl` for `_LoginData`. We would then generate the same names for `LoginData`, meaning that you can't have `LoginData` and `_LoginData` in the same module.

Or we could just live with the double underscore.

@tvh any preferences?

**Comment by tvh** [comment]
`built_value` avoids this problem by introducing `$` into the names of generated things. This also deals with the issue that you can't define a `LoginDataImpl`. Maybe something like this?

```.dart
mixin _LoginData in __LoginDataBase {}
mixin __LoginDataBase {}
abstract class _LoginDataFactory {}
class _LoginDataImpl$
```

**Comment by skogsbaer** [comment]
I don't see how the `$` would solve the problem. In your example above, you still need to have two underscores in `__LoginDataBase`. But maybe we should just live with this fact. At least, the naming scheme is very predictable.

**Comment by tvh** [comment]
I think it is fine. In my example I tried to address the fact that

**Comment by skogsbaer** [comment]
I'm now closing this issue. Please reopen if necessary.
